version: '3'
services:
  web:
    build: .
    ports:
      - "443:443"
  redis:
    image: "redis:alpine"
  postgres:
    image: "postgres:alpine"
    ports:
    - "5434:5432"
    environment:
      - POSTGRES_USER=sk
      - POSTGRES_PASSWORD=kothari
      - POSTGRES_DB=skdb